version: gimble v0.5.0
random_seed: 12345
precision: 25
population_ids:
  A: chi
  B: ros
k_max:
  m_1: 2
  m_2: 2
  m_3: 2
  m_4: 2
parameters:
  C_A: 0.41474684
  C_B: 1.0
  M_B_A: 1.6522027
  theta: 0.43659064
boundaries:
  C_A:
  - MIN
  - MAX
  C_A_B:
  - MIN
  - MAX
  C_B:
  - MIN
  - MAX
  M_A_B:
  - MIN
  - MAX
  T:
  - MIN
  - MAX
  theta:
  - MIN
  - MAX
