version: gimble v0.5.0
model: /Users/s1854903/git/gIMble/output/test.model.tsv
precision: 25
blocks: 1
blocklength: 64
replicates: 100000
parameters:
  C_A: 0.5
  C_A_B: 0.5
  C_B: 0.285861300097193
  M_B_A: 3.8951
  T: inf
  sample_size_A: 1
  sample_size_B: 1
  theta: 0.0159328125
boundaries:
  C_A:
  - MIN
  - MAX
  - STEPSIZE
  C_A_B:
  - MIN
  - MAX
  - STEPSIZE
  C_B:
  - MIN
  - MAX
  - STEPSIZE
  M_B_A:
  - MIN
  - MAX
  - STEPSIZE
  T:
  - MIN
  - MAX
  - STEPSIZE
  theta:
  - MIN
  - MAX
  - STEPSIZE
recombination:
  cutoff: INT
  number_bins: INT
  rate: FLOAT
  recombination_map: FILE_PATH 
  scale: LINEAR
grid:
  file: FILE_PATH 
ploidy: 2
