{% set name = "giacpy" %}
{% set version = "0.6.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e3117a14c31eeefe4631b2a917de4f26429fda82fffed3be6d1768b2f8393e0f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - giacpy

about:
  home: http://www.imj-prg.fr/~frederic.han/xcas/giacpy/
  license: GPLv2 or above
  license_family: GPL2
  license_file: 
  summary: A Cython frontend to the c++ library giac. (Computer Algebra System)
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
