version: gimble v0.5.0
random_seed: 12345
precision: 25
model: /Users/dlaetsch/git/gIMble/models/graph.s_A_B.p2.n_1_1.m_AtoB.model.tsv
population_ids:
  A: STRING
  B: STRING
k_max:
  m_1: INT
  m_2: INT
  m_3: INT
  m_4: INT
parameters:
  C_A: FLOAT
  C_B: FLOAT
  M_A_B: FLOAT
  T: FLOAT
  theta: FLOAT
boundaries:
  C_A:
  - MIN
  - MAX
  C_B:
  - MIN
  - MAX
  M_A_B:
  - MIN
  - MAX
  T:
  - MIN
  - MAX
  theta:
  - MIN
  - MAX
