version: gimble v0.5.0
model: /Users/dlaetsch/git/gIMble/graph.s_A_B.p2.n_1_1.m_BtoA.model.tsv
random_seed: 12345
precision: 25
k_max:
  m_1: 3
  m_2: 3
  m_3: 3
  m_4: 3
parameters:
  C_A: 1
  C_B: 1
  M_B_A: 2.34
  T: 1.4
  theta: 1.2
boundaries:
  C_A:
  - MIN
  - MAX
  C_B:
  - MIN
  - MAX
  M_B_A:
  - MIN
  - MAX
  T:
  - MIN
  - MAX
  theta:
  - MIN
  - MAX
